# ESTRUTURAS CONDICIONAIS
"""
idade = int(input("Digite sua idade:"))
if idade >= 18:
    print("Você é maior de idade")
else:
    print("Vocé é menor de idade")
"""

"""
  Imagine que você queira imprimir "Aprovado", caso o estudade tenha uma média supeirior ou igual a 7, e "Reprovado",
  caso a média seja inferior a 7.
"""
"""
media = float(input( "Digite sua média:"))
if media >= 7:
    print("Você está Aprovado")
elif media <= 5:
    print("Você está em Recuperação")
else: 
    print("Você está Reprovado")
"""
######

media = 50
presenca = 100

if media >= 70 and presenca >= 100:
    print("Voce está Aprovado!")
else:
    print("Você está Reprovado!")